#!/bin/bash
alias dr="docker-compose run laravel"
alias php="dr php"
alias artisan="php artisan"
alias __do__test="artisan test"
alias tst="artisan config:cache && alias tst=__do__test && __do__test"
alias up="docker-compose down && docker-compose up"
alias 0db="docker-compose run laravel bash startupClean.sh"
alias savedb="sudo rm -f laravel/database/database.sqlite.presentation && sudo cp laravel/database/database.sqlite laravel/database/database.sqlite.presentation"